/* Auto-loaded by expand-catalog-5.ts. Real, public websites (online services).
 * [slug, name, domain, pricing, tagline, tagsCSV, platformsCSV?, openSource?] */
export const ROWS: (string | boolean)[][] = [
  // ── File / media converters & utilities ──
  ["convertio","Convertio","convertio.co","FREEMIUM","Convert files between hundreds of formats","converter,files,tools"],
  ["cloudconvert","CloudConvert","cloudconvert.com","FREEMIUM","Online file converter for any format","converter,files,tools"],
  ["zamzar","Zamzar","zamzar.com","FREEMIUM","Convert and compress files online","converter,files,tools"],
  ["freeconvert","FreeConvert","freeconvert.com","FREEMIUM","Free online file converter","converter,files,tools"],
  ["tinywow","TinyWow","tinywow.com","FREE","Free PDF, image and file tools","pdf,files,tools"],
  ["ezgif","EZGIF","ezgif.com","FREE","Simple online GIF maker and editor","gif,image-editing,tools"],
  ["pdfcandy","PDF Candy","pdfcandy.com","FREEMIUM","Free online PDF toolkit","pdf,converter,tools"],
  ["compressor-io","Compressor.io","compressor.io","FREE","Compress images without losing quality","image-optimization,tools,files"],
  ["iloveimg","iLoveIMG","iloveimg.com","FREEMIUM","Online image editing and compression","image-editing,tools,files"],
  ["picsum","Lorem Picsum","picsum.photos","FREE","Easy placeholder images for developers","developer,images,placeholder"],
  ["remove-video-bg","Unscreen","unscreen.com","FREEMIUM","Remove video backgrounds automatically","video,ai,tools"],
  // ── Developer utilities ──
  ["cyberchef","CyberChef","gchq.github.io/CyberChef","FREE","The cyber Swiss-army knife for data","developer,security,tools","web",true],
  ["jwt-io","JWT.io","jwt.io","FREE","Decode and verify JSON Web Tokens","developer,security,tools"],
  ["regexr","RegExr","regexr.com","FREE","Learn, build and test regular expressions","regex,developer,tools"],
  ["crontab-guru","Crontab Guru","crontab.guru","FREE","The quick and simple cron schedule editor","developer,cron,tools"],
  ["json-placeholder","JSONPlaceholder","jsonplaceholder.typicode.com","FREE","Free fake REST API for testing","developer,api,testing"],
  ["reqres-in","Reqres","reqres.in","FREE","Hosted REST API to prototype against","developer,api,testing"],
  ["mocky-io","Mocky","mocky.io","FREE","Generate custom HTTP mock responses","developer,api,testing"],
  ["shields-io","Shields.io","shields.io","FREE","Quality metadata badges for your repos","developer,badges,tools","web",true],
  ["readme-so","readme.so","readme.so","FREE","Easily create a README for your project","developer,documentation,tools"],
  ["chalk-ist","Chalk.ist","chalk.ist","FREE","Create beautiful images of your code","developer,design,screenshots"],
  ["mermaid-live","Mermaid Live Editor","mermaid.live","FREE","Create diagrams from text online","diagrams,developer,tools","web",true],
  ["asciiflow","ASCIIFlow","asciiflow.com","FREE","Draw ASCII diagrams in your browser","diagrams,developer,tools"],
  ["epoch-converter","Epoch Converter","epochconverter.com","FREE","Convert Unix timestamps and dates","developer,tools,reference"],
  ["diffchecker","Diffchecker","diffchecker.com","FREEMIUM","Compare text and files for differences","developer,tools,text"],
  ["quicktype","quicktype","quicktype.io","FREE","Generate types and models from JSON","developer,json,tools","web",true],
  ["transform-tools","Transform","transform.tools","FREE","Convert between many code formats","developer,converter,tools"],
  ["bundlephobia","Bundlephobia","bundlephobia.com","FREE","Find the cost of adding an npm package","developer,npm,tools"],
  ["npm-trends","npm trends","npmtrends.com","FREE","Compare npm package downloads over time","developer,npm,tools"],
  ["roadmap-sh","roadmap.sh","roadmap.sh","FREE","Developer roadmaps and learning paths","developer,learning,reference","web",true],
  ["javascript-info","JavaScript.info","javascript.info","FREE","The modern JavaScript tutorial","developer,learning,javascript"],
  ["programiz","Programiz","programiz.com","FREEMIUM","Learn programming with tutorials","developer,learning,coding"],
  ["geeksforgeeks","GeeksforGeeks","geeksforgeeks.org","FREEMIUM","Computer science portal and tutorials","developer,learning,reference"],
  ["tutorialspoint","Tutorialspoint","tutorialspoint.com","FREEMIUM","Tutorials for programming and tech","learning,reference,coding"],
  ["theodinproject","The Odin Project","theodinproject.com","FREE","Free full-stack curriculum","developer,learning,coding","web",true],
  ["fullstackopen","Full Stack Open","fullstackopen.com","FREE","Deep dive into modern web development","developer,learning,coding"],
  ["cssbattle","CSSBattle","cssbattle.dev","FREEMIUM","Code golf with CSS challenges","developer,css,challenges"],
  ["flexbox-froggy","Flexbox Froggy","flexboxfroggy.com","FREE","A game for learning CSS flexbox","developer,css,learning"],
  ["codingame","CodinGame","codingame.com","FREEMIUM","Improve coding skills by playing games","developer,coding,challenges"],
  ["advent-of-code","Advent of Code","adventofcode.com","FREE","Annual programming puzzle calendar","developer,coding,challenges"],
  ["project-euler","Project Euler","projecteuler.net","FREE","Mathematical programming challenges","developer,math,challenges"],
  ["codeforces","Codeforces","codeforces.com","FREE","Competitive programming contests","developer,coding,competitive"],
  ["codechef","CodeChef","codechef.com","FREEMIUM","Competitive programming platform","developer,coding,competitive"],
  ["explainshell","explainshell","explainshell.com","FREE","Explain any shell command","developer,cli,reference","web",true],
  ["quickref-me","QuickRef.ME","quickref.me","FREE","Quick reference cheat sheets","developer,reference,cli","web",true],
  // ── Web performance / security checkers ──
  ["gtmetrix","GTmetrix","gtmetrix.com","FREEMIUM","Analyze your page speed and performance","seo,performance,tools"],
  ["webpagetest","WebPageTest","webpagetest.org","FREEMIUM","Detailed website performance testing","performance,developer,tools"],
  ["securityheaders","Security Headers","securityheaders.com","FREE","Scan your site's HTTP security headers","security,developer,tools"],
  ["ssllabs","SSL Labs","ssllabs.com","FREE","Deep analysis of your SSL configuration","security,ssl,tools"],
  ["mxtoolbox","MXToolbox","mxtoolbox.com","FREEMIUM","DNS, email and network diagnostics","dns,email,tools"],
  ["whatsmydns","What's My DNS","whatsmydns.net","FREE","Check DNS propagation worldwide","dns,developer,tools"],
  ["dnschecker","DNS Checker","dnschecker.org","FREE","DNS propagation and lookup tools","dns,network,tools"],
  ["builtwith","BuiltWith","builtwith.com","FREEMIUM","Find out what websites are built with","seo,developer,research"],
  ["urlscan","urlscan.io","urlscan.io","FREEMIUM","Scan and analyze suspicious URLs","security,research,tools"],
  ["virustotal","VirusTotal","virustotal.com","FREEMIUM","Analyze files and URLs for malware","security,research,tools"],
  // ── SEO / research ──
  ["answerthepublic","AnswerThePublic","answerthepublic.com","FREEMIUM","Discover what people search for","seo,research,keywords"],
  ["alsoasked","AlsoAsked","alsoasked.com","FREEMIUM","People-also-ask keyword research","seo,research,keywords"],
  ["keywordtool-io","Keyword Tool","keywordtool.io","FREEMIUM","Find keywords from autocomplete","seo,research,keywords"],
  ["google-trends","Google Trends","trends.google.com","FREE","Explore what the world is searching","seo,research,trends"],
  ["exploding-topics","Exploding Topics","explodingtopics.com","FREEMIUM","Discover trending topics before they take off","seo,research,trends"],
  ["similarweb-site","Similarweb","similarweb.com","FREEMIUM","Website traffic and market analytics","seo,analytics,research"],
  ["wordcounter","WordCounter","wordcounter.net","FREE","Count words and characters online","writing,tools,text"],
  ["quetext","Quetext","quetext.com","FREEMIUM","Plagiarism checker for writers","writing,plagiarism,tools"],
  ["copyscape","Copyscape","copyscape.com","FREEMIUM","Detect duplicate content and plagiarism","writing,plagiarism,seo"],
  // ── Design resources: icons, illustrations, colors ──
  ["colorhunt","Color Hunt","colorhunt.co","FREE","Curated color palettes for designers","design,color,inspiration"],
  ["adobe-color","Adobe Color","color.adobe.com","FREE","Create and explore color palettes","design,color,tools"],
  ["realtime-colors","Realtime Colors","realtimecolors.com","FREE","Preview color palettes on a real site","design,color,tools"],
  ["uigradients","uiGradients","uigradients.com","FREE","Beautiful ready-made CSS gradients","design,color,css","web",true],
  ["cssgradient-io","CSS Gradient","cssgradient.io","FREE","Generate CSS gradients visually","design,css,tools"],
  ["haikei","Haikei","haikei.app","FREE","Generate SVG shapes and backgrounds","design,svg,tools"],
  ["blobmaker","Blobmaker","blobmaker.app","FREE","Make organic SVG blob shapes","design,svg,tools"],
  ["undraw","unDraw","undraw.co","FREE","Open source illustrations for any project","design,illustrations,resources"],
  ["storyset","Storyset","storyset.com","FREE","Customizable illustrations by Freepik","design,illustrations,resources"],
  ["svgrepo","SVG Repo","svgrepo.com","FREE","Free open-licensed SVG vectors and icons","design,icons,svg"],
  ["iconscout","Iconscout","iconscout.com","FREEMIUM","Icons, illustrations and 3D assets","design,icons,resources"],
  ["thenounproject","The Noun Project","thenounproject.com","FREEMIUM","Icons and photos for everything","design,icons,resources"],
  ["svg-icons8","Icons8","icons8.com","FREEMIUM","Icons, illustrations, photos and music","design,icons,resources"],
  ["simpleicons","Simple Icons","simpleicons.org","FREE","SVG icons for popular brands","design,icons,developer","web",true],
  ["heroicons","Heroicons","heroicons.com","FREE","Beautiful hand-crafted SVG icons","design,icons,developer","web",true],
  ["lucide-icons","Lucide","lucide.dev","FREE","Beautiful and consistent open source icons","design,icons,developer","web",true],
  ["tabler-icons","Tabler Icons","tabler.io/icons","FREE","Free open source SVG icons","design,icons,developer","web",true],
  ["iconfinder","Iconfinder","iconfinder.com","FREEMIUM","Marketplace for icons and illustrations","design,icons,resources"],
  // ── Fonts ──
  ["dafont","DaFont","dafont.com","FREE","Archive of free downloadable fonts","design,fonts,resources"],
  ["fontsquirrel","Font Squirrel","fontsquirrel.com","FREE","Free fonts for commercial use","design,fonts,resources"],
  ["fontshare","Fontshare","fontshare.com","FREE","Quality fonts, free for personal and commercial","design,fonts,resources"],
  ["fontpair","Fontpair","fontpair.co","FREE","Find great Google Font pairings","design,fonts,inspiration"],
  ["typewolf","Typewolf","typewolf.com","FREEMIUM","Typography inspiration and font guides","design,fonts,inspiration"],
  // ── Stock photos, video, audio ──
  ["stocksnap","StockSnap.io","stocksnap.io","FREE","Free high-resolution stock photos","photos,stock,resources"],
  ["burst","Burst","burst.shopify.com","FREE","Free stock photos by Shopify","photos,stock,resources"],
  ["coverr","Coverr","coverr.co","FREE","Free stock videos for your projects","video,stock,resources"],
  ["mixkit","Mixkit","mixkit.co","FREE","Free stock video, music and templates","video,audio,resources"],
  ["freesound","Freesound","freesound.org","FREE","Collaborative library of free sounds","audio,resources,open-source","web",true],
  ["bensound","Bensound","bensound.com","FREEMIUM","Royalty-free music for creators","audio,music,resources"],
  ["uppbeat","Uppbeat","uppbeat.io","FREEMIUM","Free music for content creators","audio,music,resources"],
  ["freemusicarchive","Free Music Archive","freemusicarchive.org","FREE","Free-to-use music library","audio,music,resources"],
  ["pixabay-music","Pixabay Music","pixabay.com/music","FREE","Royalty-free music and sound effects","audio,music,resources"],
  // ── Learning / reference ──
  ["classcentral","Class Central","classcentral.com","FREEMIUM","Search engine for online courses","learning,courses,reference"],
  ["mit-ocw","MIT OpenCourseWare","ocw.mit.edu","FREE","Free MIT course materials online","learning,courses,free"],
  ["project-gutenberg","Project Gutenberg","gutenberg.org","FREE","Over 70,000 free ebooks","books,reading,free","web",true],
  ["openlibrary","Open Library","openlibrary.org","FREE","A web page for every book ever published","books,reading,reference","web",true],
  ["wikihow","wikiHow","wikihow.com","FREEMIUM","How-to guides for almost everything","reference,howto,learning"],
  ["desmos","Desmos","desmos.com","FREE","Beautiful, free online graphing calculator","math,education,tools"],
  ["geogebra","GeoGebra","geogebra.org","FREE","Free math tools for graphing and geometry","math,education,tools"],
  ["sparknotes","SparkNotes","sparknotes.com","FREE","Study guides and literature summaries","education,study,reference"],
  ["brainly","Brainly","brainly.com","FREEMIUM","Homework help community for students","education,study,community"],
  ["monkeytype","Monkeytype","monkeytype.com","FREE","Minimalist customizable typing test","typing,tools,open-source","web",true],
  ["keybr","keybr","keybr.com","FREE","Learn touch typing the smart way","typing,learning,tools"],
  // ── Movies / music / entertainment databases ──
  ["imdb","IMDb","imdb.com","FREEMIUM","The world's movie and TV database","movies,tv,reference"],
  ["rottentomatoes","Rotten Tomatoes","rottentomatoes.com","FREE","Movie and TV reviews and ratings","movies,tv,reviews"],
  ["metacritic","Metacritic","metacritic.com","FREE","Reviews for games, movies, TV and music","reviews,movies,games"],
  ["tmdb","The Movie Database","themoviedb.org","FREEMIUM","Community movie and TV database and API","movies,tv,api"],
  ["justwatch","JustWatch","justwatch.com","FREE","Find where to stream any movie or show","movies,streaming,search"],
  ["trakt-tv","Trakt","trakt.tv","FREEMIUM","Track the TV and movies you watch","movies,tv,tracking"],
  ["myanimelist","MyAnimeList","myanimelist.net","FREE","Track and discover anime and manga","anime,tracking,community"],
  ["anilist","AniList","anilist.co","FREE","Anime and manga tracking community","anime,tracking,community"],
  ["genius","Genius","genius.com","FREEMIUM","Song lyrics and music knowledge","music,lyrics,reference"],
  ["lastfm","Last.fm","last.fm","FREE","Track your music and discover more","music,tracking,discovery"],
  ["discogs","Discogs","discogs.com","FREEMIUM","Database and marketplace for music","music,database,marketplace"],
  // ── News / reading ──
  ["feedly","Feedly","feedly.com","FREEMIUM","Organize and read all your news feeds","news,rss,reading"],
  ["inoreader","Inoreader","inoreader.com","FREEMIUM","Powerful RSS feed reader","news,rss,reading"],
  ["ground-news","Ground News","ground.news","FREEMIUM","Compare news coverage across sources","news,reading,research"],
  ["techmeme","Techmeme","techmeme.com","FREE","Top technology news in one place","news,tech,reading"],
  ["instapaper","Instapaper","instapaper.com","FREEMIUM","Save and read articles later","reading,read-later,productivity"],
  ["omnivore","Omnivore","omnivore.app","FREE","Open source read-it-later app","reading,read-later,open-source","web",true],
  ["readwise","Readwise","readwise.io","FREEMIUM","Revisit and remember what you read","reading,notes,productivity"],
  // ── Finance / markets ──
  ["yahoo-finance","Yahoo Finance","finance.yahoo.com","FREEMIUM","Stock quotes, news and portfolio tools","finance,stocks,news"],
  ["investing-com","Investing.com","investing.com","FREEMIUM","Financial markets data and news","finance,stocks,news"],
  ["coinmarketcap","CoinMarketCap","coinmarketcap.com","FREE","Crypto prices, charts and market caps","crypto,finance,data"],
  ["coingecko","CoinGecko","coingecko.com","FREEMIUM","Independent crypto data platform","crypto,finance,data"],
  ["finviz","Finviz","finviz.com","FREEMIUM","Stock screener and market visualization","finance,stocks,screener"],
  ["stockanalysis","StockAnalysis","stockanalysis.com","FREEMIUM","Detailed stock data and financials","finance,stocks,research"],
  // ── Shopping / deals ──
  ["slickdeals","Slickdeals","slickdeals.net","FREE","Community-driven deals and coupons","shopping,deals,community"],
  ["camelcamelcamel","CamelCamelCamel","camelcamelcamel.com","FREE","Amazon price tracker and history","shopping,deals,tracking"],
  ["keepa","Keepa","keepa.com","FREEMIUM","Amazon price history and alerts","shopping,deals,tracking"],
  ["pcpartpicker","PCPartPicker","pcpartpicker.com","FREE","Plan and price your PC build","hardware,shopping,tools"],
  // ── Travel ──
  ["kayak","KAYAK","kayak.com","FREE","Search flights, hotels and cars","travel,flights,search"],
  ["rome2rio","Rome2Rio","rome2rio.com","FREEMIUM","How to get anywhere by any transport","travel,navigation,search"],
  ["flightradar24","Flightradar24","flightradar24.com","FREEMIUM","Live flight tracking worldwide","travel,tracking,maps"],
  ["nomadlist","Nomad List","nomadlist.com","SUBSCRIPTION","Best cities to live and work remotely","travel,remote,community"],
  ["hostelworld","Hostelworld","hostelworld.com","FREE","Book hostels around the world","travel,booking,budget"],
  // ── Weather / maps ──
  ["windy","Windy.com","windy.com","FREEMIUM","Interactive weather and wind maps","weather,maps,tools"],
  ["accuweather","AccuWeather","accuweather.com","FREEMIUM","Local and global weather forecasts","weather,forecast,tools"],
  ["openstreetmap","OpenStreetMap","openstreetmap.org","FREE","Free, editable map of the world","maps,navigation,open-source","web",true],
  // ── Health ──
  ["healthline","Healthline","healthline.com","FREE","Trusted health information and advice","health,reference,wellness"],
  ["webmd","WebMD","webmd.com","FREE","Medical information and symptom checker","health,reference,wellness"],
  // ── Everyday utilities ──
  ["random-org","RANDOM.ORG","random.org","FREE","True random numbers, draws and lists","tools,utility,random"],
  ["wheelofnames","Wheel of Names","wheelofnames.com","FREE","Spin a wheel to pick a random name","tools,utility,random"],
  ["qrcode-monkey","QRCode Monkey","qrcode-monkey.com","FREE","Create custom QR codes for free","tools,qr-code,utility"],
  ["giphy","GIPHY","giphy.com","FREE","Search and share animated GIFs","gif,entertainment,tools"],
  ["tenor","Tenor","tenor.com","FREE","GIF keyboard and library","gif,entertainment,tools"],
  ["imgflip","Imgflip","imgflip.com","FREEMIUM","Meme generator and image tools","meme,tools,entertainment"],
  ["timeanddate","timeanddate.com","timeanddate.com","FREE","World clock, calendar and time tools","tools,reference,utility"],
  ["worldtimebuddy","World Time Buddy","worldtimebuddy.com","FREEMIUM","Compare time zones and plan meetings","tools,scheduling,utility"],
  ["pomofocus","Pomofocus","pomofocus.io","FREE","Customizable Pomodoro timer online","productivity,focus,tools"],
  ["rapidtables","RapidTables","rapidtables.com","FREE","Online reference, calculators and tools","tools,reference,utility"],
  ["mailinator","Mailinator","mailinator.com","FREEMIUM","Public disposable inboxes for testing","email,testing,privacy"],
  ["thispersondoesnotexist","This Person Does Not Exist","thispersondoesnotexist.com","FREE","AI-generated faces on every refresh","ai,images,tools"],
];
