/**
 * Third catalog expansion — another curated batch of real, well-known software,
 * filling remaining gaps (office suites, frameworks, antivirus, browsers,
 * streaming, more AI/design/dev/finance/education tools).
 *
 * Idempotent + safe: creates a tool only if its slug does not already exist,
 * runs on every Vercel deploy, and fails soft so it never breaks the build.
 * All data is public, factual information about real products.
 */
import { PrismaClient, type PricingModel } from "@prisma/client";

const prisma = new PrismaClient();
const favicon = (domain: string) => `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

type ToolSeed = {
  slug: string; name: string; domain: string; category: string; pricing: PricingModel;
  tagline: string; description: string; pros: string[]; cons: string[]; bestFor: string[];
  platforms: string[]; company?: string; featured?: boolean; openSource?: boolean;
  scores: [number, number, number, number]; tags: string[];
};

const TOOLS: ToolSeed[] = [
  // ── AI ──
  { slug: "dall-e", name: "DALL·E", domain: "openai.com/dall-e-3", category: "ai-tools", pricing: "FREEMIUM", company: "OpenAI",
    tagline: "OpenAI's text-to-image generator, built into ChatGPT",
    description: "DALL·E generates images from natural-language prompts and is integrated directly into ChatGPT, making high-quality image creation accessible to everyone.",
    pros: ["Great prompt understanding", "Built into ChatGPT", "Easy to use"], cons: ["Fewer fine controls", "Usage limits", "Content restrictions"],
    bestFor: ["Quick images", "ChatGPT users", "Illustrations"], platforms: ["web", "api"], scores: [80, 88, 88, 84], tags: ["image-generation", "ai", "art", "openai"] },
  { slug: "character-ai", name: "Character.AI", domain: "character.ai", category: "ai-tools", pricing: "FREEMIUM", company: "Character.AI",
    tagline: "Chat with AI characters and create your own",
    description: "Character.AI lets you chat with a huge library of user-created AI personas or build your own, popular for roleplay, companionship and entertainment.",
    pros: ["Huge character library", "Fun and creative", "Free to use"], cons: ["Content filters debated", "Can be repetitive", "Not for factual tasks"],
    bestFor: ["Roleplay", "Entertainment", "Creative writing"], platforms: ["web", "ios", "android"], scores: [76, 82, 88, 76], tags: ["chatbot", "ai", "roleplay", "entertainment"] },
  { slug: "poe", name: "Poe", domain: "poe.com", category: "ai-tools", pricing: "FREEMIUM", company: "Quora",
    tagline: "One app to chat with many AI models",
    description: "Poe by Quora gives access to many leading AI models — GPT, Claude, Gemini and more — plus custom bots, from a single subscription.",
    pros: ["Many models in one place", "Custom bots", "One subscription"], cons: ["Message limits", "Not the raw model UIs", "Costs for heavy use"],
    bestFor: ["Comparing models", "AI power users", "Custom bots"], platforms: ["web", "ios", "android"], scores: [78, 84, 82, 80], tags: ["chatbot", "ai", "llm", "aggregator"] },
  { slug: "mistral-ai", name: "Mistral AI (Le Chat)", domain: "mistral.ai", category: "ai-tools", pricing: "FREEMIUM", company: "Mistral AI", openSource: true,
    tagline: "European AI with strong open-weight models",
    description: "Mistral AI builds capable open-weight and commercial LLMs and offers Le Chat, a fast assistant, appealing to those wanting European, open alternatives.",
    pros: ["Open-weight models", "Fast responses", "European & privacy-minded"], cons: ["Smaller ecosystem", "Less multimodal", "Newer brand"],
    bestFor: ["Developers", "Open models", "Privacy-minded users"], platforms: ["web", "api", "ios", "android"], scores: [82, 86, 80, 83], tags: ["llm", "ai", "open-source", "chatbot"] },
  { slug: "quillbot", name: "QuillBot", domain: "quillbot.com", category: "ai-tools", pricing: "FREEMIUM", company: "QuillBot",
    tagline: "AI paraphrasing, grammar and writing tools",
    description: "QuillBot helps rewrite, summarize and improve text with a paraphraser, grammar checker and citation tools, popular with students and writers.",
    pros: ["Great paraphrasing", "Grammar & summarizer", "Good free tier"], cons: ["Word limits on free", "Can alter meaning", "Academic integrity concerns"],
    bestFor: ["Students", "Writers", "Paraphrasing"], platforms: ["web", "chrome", "windows", "macos"], scores: [78, 82, 86, 80], tags: ["writing", "ai", "paraphrasing", "grammar"] },
  { slug: "photoroom", name: "PhotoRoom", domain: "photoroom.com", category: "photo-editing", pricing: "FREEMIUM", company: "PhotoRoom",
    tagline: "AI background removal and product photo editing",
    description: "PhotoRoom removes backgrounds and creates professional product photos with AI, popular with e-commerce sellers and marketers.",
    pros: ["Fast background removal", "Great for e-commerce", "Templates"], cons: ["Watermark/limits on free", "Subscription for pro", "Occasional edge errors"],
    bestFor: ["E-commerce sellers", "Product photos", "Marketers"], platforms: ["web", "ios", "android"], scores: [78, 84, 84, 80], tags: ["photo-editing", "ai", "background-removal", "ecommerce"] },
  { slug: "remove-bg", name: "remove.bg", domain: "remove.bg", category: "photo-editing", pricing: "FREEMIUM", company: "Kaleido",
    tagline: "Remove image backgrounds automatically in seconds",
    description: "remove.bg instantly deletes the background from any photo using AI, with an API and integrations for designers and developers.",
    pros: ["Instant & accurate", "Simple API", "No skills needed"], cons: ["Credits for HD", "Only background removal", "Costs at scale"],
    bestFor: ["Quick cutouts", "Developers", "Designers"], platforms: ["web", "windows", "macos", "api"], scores: [79, 82, 86, 83], tags: ["photo-editing", "ai", "background-removal", "design"] },
  { slug: "freepik", name: "Freepik", domain: "freepik.com", category: "photo-editing", pricing: "FREEMIUM", company: "Freepik",
    tagline: "Stock images, vectors and AI creative tools",
    description: "Freepik offers millions of stock photos, vectors and templates, plus a growing suite of AI image and design generators.",
    pros: ["Huge asset library", "AI tools added", "Good value"], cons: ["Attribution on free", "Subscription for full access", "Quality varies"],
    bestFor: ["Designers", "Marketers", "Stock assets"], platforms: ["web"], scores: [78, 80, 88, 82], tags: ["stock", "design", "vectors", "ai"] },
  { slug: "adobe-firefly", name: "Adobe Firefly", domain: "adobe.com/products/firefly", category: "ai-tools", pricing: "FREEMIUM", company: "Adobe",
    tagline: "Adobe's commercially-safe generative AI",
    description: "Adobe Firefly generates images and effects trained on licensed content, integrated across Photoshop and Creative Cloud for commercial-safe AI.",
    pros: ["Commercially safe", "Creative Cloud integration", "Good text effects"], cons: ["Credits system", "Needs Adobe account", "Less edgy than rivals"],
    bestFor: ["Designers", "Commercial work", "Adobe users"], platforms: ["web", "windows", "macos"], scores: [79, 85, 84, 85], tags: ["image-generation", "ai", "adobe", "design"] },
  { slug: "phind", name: "Phind", domain: "phind.com", category: "ai-tools", pricing: "FREEMIUM", company: "Phind",
    tagline: "AI search and answer engine for developers",
    description: "Phind is an AI answer engine tuned for developers, giving code-aware answers with sources and examples for technical questions.",
    pros: ["Developer-focused answers", "Cites sources", "Good for debugging"], cons: ["Narrower use case", "Limits on free", "Less general"],
    bestFor: ["Developers", "Debugging", "Technical search"], platforms: ["web"], scores: [78, 84, 78, 80], tags: ["search", "ai", "developer", "coding"] },

  // ── Office / Docs / Productivity ──
  { slug: "google-docs", name: "Google Docs", domain: "docs.google.com", category: "productivity", pricing: "FREEMIUM", company: "Google", featured: true,
    tagline: "Free, real-time collaborative document editing",
    description: "Google Docs is a free, browser-based word processor with seamless real-time collaboration, comments and revision history, part of Google Workspace.",
    pros: ["Free & real-time collab", "Auto-save & history", "Works anywhere"], cons: ["Fewer advanced features than Word", "Needs internet ideally", "Privacy considerations"],
    bestFor: ["Collaboration", "Students", "Everyday docs"], platforms: ["web", "ios", "android"], scores: [82, 78, 95, 90], tags: ["documents", "collaboration", "google", "office"] },
  { slug: "google-sheets", name: "Google Sheets", domain: "sheets.google.com", category: "productivity", pricing: "FREEMIUM", company: "Google",
    tagline: "Free collaborative spreadsheets in the browser",
    description: "Google Sheets is a powerful, free online spreadsheet with real-time collaboration, formulas, charts and scripting via Apps Script.",
    pros: ["Free & collaborative", "Powerful formulas", "Apps Script automation"], cons: ["Slower on huge datasets", "Fewer power features than Excel", "Online-first"],
    bestFor: ["Collaboration", "Data tracking", "Small teams"], platforms: ["web", "ios", "android"], scores: [82, 78, 93, 89], tags: ["spreadsheet", "collaboration", "google", "office"] },
  { slug: "microsoft-excel", name: "Microsoft Excel", domain: "microsoft.com/excel", category: "productivity", pricing: "SUBSCRIPTION", company: "Microsoft", featured: true,
    tagline: "The industry-standard spreadsheet application",
    description: "Microsoft Excel is the gold-standard spreadsheet for data analysis, modeling and reporting, with pivot tables, Power Query and countless functions.",
    pros: ["Unmatched power", "Pivot tables & Power Query", "Industry standard"], cons: ["Subscription (Microsoft 365)", "Steep for advanced use", "Overkill for simple needs"],
    bestFor: ["Data analysis", "Finance", "Reporting"], platforms: ["windows", "macos", "web", "ios", "android"], scores: [82, 80, 95, 92], tags: ["spreadsheet", "office", "microsoft", "data"] },
  { slug: "roam-research", name: "Roam Research", domain: "roamresearch.com", category: "productivity", pricing: "SUBSCRIPTION", company: "Roam Research",
    tagline: "Networked note-taking for connected thought",
    description: "Roam Research pioneered bidirectional linking and the daily-notes workflow for building a personal knowledge graph, loved by researchers and writers.",
    pros: ["Powerful bidirectional links", "Graph of ideas", "Great for research"], cons: ["Pricey", "Steep learning curve", "Performance at scale"],
    bestFor: ["Researchers", "Writers", "PKM"], platforms: ["web", "windows", "macos"], scores: [79, 76, 74, 80], tags: ["notes", "pkm", "productivity", "research"] },
  { slug: "craft-docs", name: "Craft", domain: "craft.do", category: "productivity", pricing: "FREEMIUM", company: "Craft",
    tagline: "Beautiful documents and notes for Apple users",
    description: "Craft is a gorgeously designed notes and docs app with blocks, backlinks and polished sharing, especially strong on Apple platforms.",
    pros: ["Beautiful design", "Great on Apple", "Nice sharing"], cons: ["Apple-first", "Best features paid", "Smaller ecosystem"],
    bestFor: ["Apple users", "Notes", "Polished docs"], platforms: ["macos", "ios", "web", "windows"], scores: [79, 74, 78, 82], tags: ["notes", "documents", "apple", "productivity"] },
  { slug: "bear-app", name: "Bear", domain: "bear.app", category: "productivity", pricing: "FREEMIUM", company: "Shiny Frog",
    tagline: "Elegant markdown notes for Apple devices",
    description: "Bear is a beautiful, flexible markdown note-taking app for Apple platforms with tags, linking and a distraction-free writing experience.",
    pros: ["Lovely writing experience", "Markdown & tags", "Fast"], cons: ["Apple only", "Sync needs Pro", "Basic collaboration"],
    bestFor: ["Writers", "Apple users", "Markdown notes"], platforms: ["macos", "ios"], scores: [78, 72, 78, 84], tags: ["notes", "markdown", "apple", "writing"] },
  { slug: "joplin", name: "Joplin", domain: "joplinapp.org", category: "productivity", pricing: "OPEN_SOURCE", company: "Joplin", openSource: true,
    tagline: "Open-source, encrypted markdown note-taking",
    description: "Joplin is a free, open-source note and to-do app with markdown, end-to-end encryption and flexible sync options, a private Evernote alternative.",
    pros: ["Free & open source", "End-to-end encryption", "Flexible sync"], cons: ["Less polished", "Sync setup", "Web clipper basic"],
    bestFor: ["Privacy", "Markdown notes", "Open-source fans"], platforms: ["windows", "macos", "linux", "ios", "android"], scores: [81, 72, 76, 86], tags: ["notes", "open-source", "markdown", "privacy"] },
  { slug: "motion", name: "Motion", domain: "usemotion.com", category: "productivity", pricing: "SUBSCRIPTION", company: "Motion",
    tagline: "AI calendar that auto-plans your tasks and meetings",
    description: "Motion uses AI to automatically schedule your tasks around meetings on a smart calendar, rebuilding your day as priorities change.",
    pros: ["Automatic scheduling", "Combines tasks & calendar", "Reduces planning"], cons: ["Expensive", "Learning curve", "Rigid at times"],
    bestFor: ["Busy professionals", "Time-blocking", "Managers"], platforms: ["web", "ios", "android", "chrome"], scores: [78, 82, 78, 79], tags: ["calendar", "ai", "productivity", "scheduling"] },
  { slug: "fantastical", name: "Fantastical", domain: "flexibits.com/fantastical", category: "productivity", pricing: "FREEMIUM", company: "Flexibits",
    tagline: "Award-winning calendar app for Apple devices",
    description: "Fantastical is a powerful, beautifully designed calendar and tasks app for Apple platforms with natural-language input and rich scheduling features.",
    pros: ["Beautiful & powerful", "Natural language input", "Great integrations"], cons: ["Apple only", "Subscription for full features", "Pricey"],
    bestFor: ["Apple users", "Scheduling", "Power users"], platforms: ["macos", "ios"], scores: [78, 74, 80, 85], tags: ["calendar", "apple", "productivity", "scheduling"] },

  // ── Design ──
  { slug: "adobe-xd", name: "Adobe XD", domain: "adobe.com/products/xd", category: "photo-editing", pricing: "FREEMIUM", company: "Adobe",
    tagline: "UI/UX design and prototyping tool",
    description: "Adobe XD is a vector-based UI/UX design and prototyping tool with Creative Cloud integration, though development focus has slowed since Figma's rise.",
    pros: ["Good prototyping", "Creative Cloud integration", "Vector-based"], cons: ["Development slowed", "Lost ground to Figma", "Fewer plugins"],
    bestFor: ["UI design", "Prototyping", "Adobe users"], platforms: ["windows", "macos"], scores: [76, 74, 76, 82], tags: ["ui", "design", "prototyping", "adobe"] },
  { slug: "invision", name: "InVision", domain: "invisionapp.com", category: "photo-editing", pricing: "FREEMIUM", company: "InVision",
    tagline: "Digital product design and prototyping platform",
    description: "InVision offered prototyping and design collaboration tools; it popularized clickable prototypes though its design tools have wound down over time.",
    pros: ["Clickable prototypes", "Design feedback", "Freehand whiteboard"], cons: ["Product wound down", "Lost users to Figma", "Uncertain future"],
    bestFor: ["Prototyping", "Design feedback", "Whiteboarding"], platforms: ["web"], scores: [72, 70, 74, 78], tags: ["prototyping", "design", "collaboration", "ux"] },
  { slug: "spline", name: "Spline", domain: "spline.design", category: "photo-editing", pricing: "FREEMIUM", company: "Spline",
    tagline: "Design 3D scenes and interactions in the browser",
    description: "Spline is a collaborative tool for creating 3D graphics, animations and interactive scenes for the web, no coding required.",
    pros: ["Approachable 3D", "Web export", "Real-time collaboration"], cons: ["Performance heavy", "Learning curve", "Newer tool"],
    bestFor: ["3D web design", "Interactive scenes", "Designers"], platforms: ["web", "macos", "windows"], scores: [78, 78, 76, 79], tags: ["3d", "design", "web", "animation"] },
  { slug: "pixelmator-pro", name: "Pixelmator Pro", domain: "pixelmator.com", category: "photo-editing", pricing: "ONE_TIME", company: "Pixelmator",
    tagline: "Powerful, native image editor for Mac",
    description: "Pixelmator Pro is a fast, Mac-native image editor with pro tools and ML-powered features at a one-time price, a great Photoshop alternative for Mac.",
    pros: ["Native & fast on Mac", "One-time purchase", "ML features"], cons: ["Mac only", "Fewer pro features than PS", "No Windows"],
    bestFor: ["Mac users", "Photo editing", "Affordable pro editing"], platforms: ["macos"], scores: [80, 76, 78, 85], tags: ["photo-editing", "mac", "design", "affordable"] },
  { slug: "capture-one", name: "Capture One", domain: "captureone.com", category: "photo-editing", pricing: "SUBSCRIPTION", company: "Capture One",
    tagline: "Professional RAW photo editing and tethering",
    description: "Capture One is a pro-grade RAW editor prized for color grading, tethered shooting and precise controls, a Lightroom alternative for photographers.",
    pros: ["Excellent color & RAW", "Great tethering", "Precise controls"], cons: ["Expensive", "Steep learning curve", "Heavy"],
    bestFor: ["Professional photographers", "Studio work", "Color grading"], platforms: ["windows", "macos"], scores: [78, 74, 78, 85], tags: ["photo-editing", "raw", "photography", "professional"] },

  // ── Dev / Infra ──
  { slug: "jira", name: "Jira", domain: "atlassian.com/software/jira", category: "developer-tools", pricing: "FREEMIUM", company: "Atlassian",
    tagline: "Issue tracking and agile project management for teams",
    description: "Jira is the leading agile project management tool for software teams, with scrum/kanban boards, backlogs, sprints and deep DevOps integrations.",
    pros: ["Powerful for agile", "Highly configurable", "Deep integrations"], cons: ["Complex & heavy", "Can be slow", "Overkill for small teams"],
    bestFor: ["Software teams", "Agile", "Issue tracking"], platforms: ["web", "ios", "android"], scores: [80, 78, 90, 88], tags: ["project-management", "agile", "developer", "issue-tracking"] },
  { slug: "confluence", name: "Confluence", domain: "atlassian.com/software/confluence", category: "productivity", pricing: "FREEMIUM", company: "Atlassian",
    tagline: "Team workspace and wiki for documentation",
    description: "Confluence is Atlassian's team wiki for documentation, knowledge bases and collaboration, integrating tightly with Jira.",
    pros: ["Great for docs & wikis", "Jira integration", "Templates"], cons: ["Can get cluttered", "Search could be better", "Pricing at scale"],
    bestFor: ["Documentation", "Wikis", "Teams"], platforms: ["web", "ios", "android"], scores: [78, 74, 86, 86], tags: ["wiki", "documentation", "collaboration", "atlassian"] },
  { slug: "bitbucket", name: "Bitbucket", domain: "bitbucket.org", category: "developer-tools", pricing: "FREEMIUM", company: "Atlassian",
    tagline: "Git hosting with built-in CI/CD, from Atlassian",
    description: "Bitbucket is a Git repository hosting service with Pipelines CI/CD and tight Jira integration, popular with Atlassian-centric teams.",
    pros: ["Jira integration", "Built-in Pipelines", "Free private repos"], cons: ["Smaller community", "UI less loved", "Fewer features than GitHub"],
    bestFor: ["Atlassian teams", "Private repos", "CI/CD"], platforms: ["web", "cli"], scores: [78, 74, 80, 84], tags: ["git", "code-hosting", "ci-cd", "atlassian"] },
  { slug: "circleci", name: "CircleCI", domain: "circleci.com", category: "developer-tools", pricing: "FREEMIUM", company: "CircleCI",
    tagline: "Continuous integration and delivery platform",
    description: "CircleCI automates building, testing and deploying code with fast, configurable pipelines and broad language support.",
    pros: ["Fast pipelines", "Flexible config", "Good free tier"], cons: ["Config complexity", "Costs at scale", "Debugging can be tricky"],
    bestFor: ["CI/CD", "DevOps", "Developers"], platforms: ["web", "api"], scores: [80, 76, 82, 85], tags: ["ci-cd", "devops", "developer", "automation"] },
  { slug: "datadog", name: "Datadog", domain: "datadoghq.com", category: "developer-tools", pricing: "FREEMIUM", company: "Datadog",
    tagline: "Monitoring and observability for cloud applications",
    description: "Datadog unifies metrics, traces, logs and security monitoring across your infrastructure and apps, a leader in cloud observability.",
    pros: ["Comprehensive observability", "Great dashboards", "Many integrations"], cons: ["Expensive at scale", "Pricing complexity", "Can be overwhelming"],
    bestFor: ["DevOps", "SRE", "Cloud monitoring"], platforms: ["web", "api"], scores: [80, 78, 88, 88], tags: ["monitoring", "observability", "devops", "cloud"] },
  { slug: "cloudinary", name: "Cloudinary", domain: "cloudinary.com", category: "developer-tools", pricing: "FREEMIUM", company: "Cloudinary",
    tagline: "Image and video management API for developers",
    description: "Cloudinary handles image and video upload, storage, transformation and optimized delivery via a developer-friendly API and CDN.",
    pros: ["Powerful media transforms", "Great CDN delivery", "Good free tier"], cons: ["Costs at scale", "Complex pricing", "Learning curve"],
    bestFor: ["Web apps", "Media-heavy sites", "Developers"], platforms: ["web", "api"], scores: [80, 78, 82, 85], tags: ["media", "images", "cdn", "developer"] },
  { slug: "algolia", name: "Algolia", domain: "algolia.com", category: "developer-tools", pricing: "FREEMIUM", company: "Algolia",
    tagline: "Hosted search API for fast, relevant results",
    description: "Algolia provides a fast, hosted search-as-a-service API with typo tolerance, ranking and analytics for adding great search to any app.",
    pros: ["Blazing-fast search", "Great DX", "Relevance tuning"], cons: ["Pricing by usage", "Costs at scale", "Vendor lock-in"],
    bestFor: ["Site search", "E-commerce", "Developers"], platforms: ["web", "api"], scores: [80, 78, 82, 85], tags: ["search", "api", "developer", "saas"] },
  { slug: "cypress", name: "Cypress", domain: "cypress.io", category: "developer-tools", pricing: "FREEMIUM", company: "Cypress", openSource: true,
    tagline: "Fast, reliable end-to-end testing for the web",
    description: "Cypress is a developer-friendly end-to-end testing framework that runs in the browser with time-travel debugging and a great UI.",
    pros: ["Great DX", "Time-travel debugging", "Open source core"], cons: ["Browser support limits", "Paid dashboard", "Not for all test types"],
    bestFor: ["E2E testing", "Frontend devs", "QA"], platforms: ["windows", "macos", "linux", "cli"], scores: [81, 76, 82, 85], tags: ["testing", "e2e", "developer", "open-source"] },
  { slug: "playwright", name: "Playwright", domain: "playwright.dev", category: "developer-tools", pricing: "OPEN_SOURCE", company: "Microsoft", openSource: true,
    tagline: "Reliable cross-browser end-to-end testing",
    description: "Playwright is Microsoft's open-source automation framework for reliable end-to-end testing across Chromium, Firefox and WebKit.",
    pros: ["Free & open source", "Cross-browser", "Fast & reliable"], cons: ["Learning curve", "Verbose setup", "Newer than Selenium"],
    bestFor: ["E2E testing", "Automation", "Developers"], platforms: ["windows", "macos", "linux", "cli"], scores: [83, 78, 84, 88], tags: ["testing", "automation", "open-source", "developer"] },

  // ── Frameworks ──
  { slug: "nextjs", name: "Next.js", domain: "nextjs.org", category: "developer-tools", pricing: "OPEN_SOURCE", company: "Vercel", openSource: true, featured: true,
    tagline: "The React framework for the web",
    description: "Next.js is a popular open-source React framework for building full-stack web apps with server rendering, routing and optimizations built in.",
    pros: ["Full-stack React", "Great performance", "Huge ecosystem"], cons: ["Fast-changing", "Complexity growing", "Vercel-centric features"],
    bestFor: ["Web apps", "React developers", "Full-stack"], platforms: ["web", "cli", "self-hosted"], scores: [86, 80, 92, 90], tags: ["framework", "react", "web", "open-source"] },
  { slug: "react", name: "React", domain: "react.dev", category: "developer-tools", pricing: "OPEN_SOURCE", company: "Meta", openSource: true, featured: true,
    tagline: "The library for building user interfaces",
    description: "React is the most widely used JavaScript library for building component-based user interfaces, maintained by Meta and a huge community.",
    pros: ["Massive ecosystem", "Component model", "Huge job market"], cons: ["Just the view layer", "Choice overload", "Boilerplate"],
    bestFor: ["Web UIs", "Frontend devs", "SPAs"], platforms: ["web", "cli"], scores: [86, 80, 96, 92], tags: ["framework", "javascript", "ui", "open-source"] },
  { slug: "tailwindcss", name: "Tailwind CSS", domain: "tailwindcss.com", category: "developer-tools", pricing: "OPEN_SOURCE", company: "Tailwind Labs", openSource: true, featured: true,
    tagline: "A utility-first CSS framework for rapid UI",
    description: "Tailwind CSS is a utility-first CSS framework that lets you build custom designs fast with composable classes, hugely popular in modern web dev.",
    pros: ["Rapid styling", "Consistent design", "No naming battles"], cons: ["Verbose HTML", "Learning curve", "Divisive approach"],
    bestFor: ["Web UI", "Frontend devs", "Design systems"], platforms: ["web", "cli"], scores: [85, 78, 94, 90], tags: ["css", "framework", "frontend", "open-source"] },
  { slug: "astro", name: "Astro", domain: "astro.build", category: "developer-tools", pricing: "OPEN_SOURCE", company: "Astro", openSource: true,
    tagline: "The web framework for content-driven websites",
    description: "Astro is a fast, content-focused web framework that ships zero JS by default and supports any UI framework, great for blogs and marketing sites.",
    pros: ["Very fast sites", "Ship less JS", "Use any UI framework"], cons: ["Less for heavy apps", "Younger ecosystem", "SSR still maturing"],
    bestFor: ["Content sites", "Blogs", "Marketing sites"], platforms: ["web", "cli"], scores: [83, 78, 82, 85], tags: ["framework", "web", "static-site", "open-source"] },

  // ── Communication ──
  { slug: "skype", name: "Skype", domain: "skype.com", category: "saas", pricing: "FREEMIUM", company: "Microsoft",
    tagline: "Classic voice, video and messaging app",
    description: "Skype offers voice and video calls, messaging and affordable international calling; a long-running app now being phased toward Microsoft Teams.",
    pros: ["Free calls & chat", "Cheap international calls", "Cross-platform"], cons: ["Being retired for Teams", "Feels dated", "Quality varies"],
    bestFor: ["Personal calls", "International calling", "Legacy users"], platforms: ["web", "windows", "macos", "linux", "ios", "android"], scores: [72, 66, 80, 80], tags: ["video-calls", "messaging", "communication", "microsoft"] },
  { slug: "webex", name: "Webex", domain: "webex.com", category: "saas", pricing: "FREEMIUM", company: "Cisco",
    tagline: "Enterprise video meetings and calling from Cisco",
    description: "Cisco Webex provides secure video meetings, calling and webinars with enterprise-grade features and hardware integrations.",
    pros: ["Enterprise security", "Reliable at scale", "Hardware ecosystem"], cons: ["Feels corporate", "Heavier app", "Pricey"],
    bestFor: ["Enterprises", "Webinars", "Secure meetings"], platforms: ["web", "windows", "macos", "ios", "android"], scores: [76, 72, 82, 86], tags: ["video-calls", "meetings", "enterprise", "communication"] },
  { slug: "element", name: "Element", domain: "element.io", category: "saas", pricing: "FREEMIUM", company: "Element", openSource: true,
    tagline: "Secure, decentralized messaging on Matrix",
    description: "Element is an open-source, end-to-end encrypted messenger built on the decentralized Matrix protocol, self-hostable for full control.",
    pros: ["Open & decentralized", "End-to-end encryption", "Self-hostable"], cons: ["Setup complexity", "UX rough edges", "Smaller network"],
    bestFor: ["Privacy", "Self-hosting", "Communities"], platforms: ["web", "windows", "macos", "linux", "ios", "android"], scores: [80, 72, 74, 84], tags: ["messaging", "open-source", "encryption", "decentralized"] },

  // ── Security / Antivirus ──
  { slug: "lastpass", name: "LastPass", domain: "lastpass.com", category: "security", pricing: "FREEMIUM", company: "LastPass",
    tagline: "Popular password manager with autofill",
    description: "LastPass stores and autofills passwords across devices with sharing and dark-web monitoring, though it has faced scrutiny after past breaches.",
    pros: ["Easy to use", "Cross-platform", "Autofill & sharing"], cons: ["Past security breaches", "Free tier restricted", "Trust concerns"],
    bestFor: ["Individuals", "Autofill", "Convenience"], platforms: ["web", "windows", "macos", "ios", "android", "chrome", "firefox"], scores: [74, 70, 82, 74], tags: ["password-manager", "security", "autofill", "privacy"] },
  { slug: "nordpass", name: "NordPass", domain: "nordpass.com", category: "security", pricing: "FREEMIUM", company: "Nord Security",
    tagline: "Password manager from the makers of NordVPN",
    description: "NordPass is a modern password manager with zero-knowledge encryption, passkeys and data-breach scanning, from the Nord Security family.",
    pros: ["Modern encryption", "Passkey support", "Clean apps"], cons: ["Free limits devices", "Newer than rivals", "Subscription for full use"],
    bestFor: ["Individuals", "Nord users", "Passkeys"], platforms: ["web", "windows", "macos", "linux", "ios", "android", "chrome"], scores: [78, 72, 80, 83], tags: ["password-manager", "security", "encryption", "privacy"] },
  { slug: "keeper", name: "Keeper", domain: "keepersecurity.com", category: "security", pricing: "FREEMIUM", company: "Keeper Security",
    tagline: "Enterprise-grade password and secrets manager",
    description: "Keeper is a security-focused password manager with strong compliance, secrets management and dark-web monitoring for individuals and businesses.",
    pros: ["Strong security & compliance", "Business features", "Good apps"], cons: ["Add-ons cost extra", "Pricey for full suite", "Complex for individuals"],
    bestFor: ["Businesses", "Compliance", "Security-focused"], platforms: ["web", "windows", "macos", "linux", "ios", "android"], scores: [77, 72, 80, 86], tags: ["password-manager", "security", "enterprise", "compliance"] },
  { slug: "malwarebytes", name: "Malwarebytes", domain: "malwarebytes.com", category: "security", pricing: "FREEMIUM", company: "Malwarebytes",
    tagline: "Anti-malware protection and cleanup",
    description: "Malwarebytes detects and removes malware, ransomware and unwanted programs, popular as both a cleanup tool and real-time protection.",
    pros: ["Great malware cleanup", "Free scanner", "Lightweight"], cons: ["Real-time needs premium", "Not a full AV suite for some", "Occasional false positives"],
    bestFor: ["Malware removal", "Extra protection", "Cleanup"], platforms: ["windows", "macos", "android", "ios"], scores: [78, 70, 86, 85], tags: ["antivirus", "security", "malware", "protection"] },
  { slug: "bitdefender", name: "Bitdefender", domain: "bitdefender.com", category: "security", pricing: "FREEMIUM", company: "Bitdefender",
    tagline: "Top-rated antivirus and internet security",
    description: "Bitdefender provides highly-rated antivirus and internet security suites with strong protection, a VPN and low system impact.",
    pros: ["Excellent detection", "Low system impact", "Feature-rich suites"], cons: ["Upsells", "VPN limited on lower tiers", "Renewal pricing"],
    bestFor: ["Home security", "Windows users", "All-round protection"], platforms: ["windows", "macos", "android", "ios"], scores: [78, 72, 86, 87], tags: ["antivirus", "security", "protection", "internet-security"] },
  { slug: "ublock-origin", name: "uBlock Origin", domain: "ublockorigin.com", category: "browser-extensions", pricing: "OPEN_SOURCE", company: "Raymond Hill", openSource: true,
    tagline: "Efficient, open-source content and ad blocker",
    description: "uBlock Origin is a free, open-source, highly efficient wide-spectrum content blocker for browsers, beloved for blocking ads and trackers with low overhead.",
    pros: ["Free & open source", "Very efficient", "Powerful filtering"], cons: ["Manifest V3 limits on Chrome", "Advanced mode is technical", "Not on all browsers equally"],
    bestFor: ["Ad blocking", "Privacy", "Everyone"], platforms: ["chrome", "firefox"], scores: [84, 74, 92, 92], tags: ["ad-blocker", "privacy", "open-source", "browser"] },

  // ── VPN ──
  { slug: "cyberghost", name: "CyberGhost", domain: "cyberghostvpn.com", category: "vpn", pricing: "SUBSCRIPTION", company: "CyberGhost",
    tagline: "Beginner-friendly VPN with many servers",
    description: "CyberGhost is an easy-to-use VPN with a huge server network, streaming-optimized servers and long-term plans at low prices.",
    pros: ["Huge server network", "Streaming servers", "Cheap long plans"], cons: ["Short plans pricey", "Speeds vary", "Ownership scrutiny"],
    bestFor: ["Streaming", "Beginners", "Budget long-term"], platforms: ["windows", "macos", "linux", "ios", "android"], scores: [77, 70, 82, 80], tags: ["vpn", "privacy", "streaming", "security"] },
  { slug: "private-internet-access", name: "Private Internet Access", domain: "privateinternetaccess.com", category: "vpn", pricing: "SUBSCRIPTION", company: "PIA",
    tagline: "Configurable VPN with a proven no-logs record",
    description: "Private Internet Access (PIA) is a highly configurable, open-source VPN with a large network and a court-proven no-logs policy.",
    pros: ["Open-source apps", "Proven no-logs", "Very configurable"], cons: ["US-based jurisdiction", "Speeds vary", "Overwhelming settings"],
    bestFor: ["Privacy tinkerers", "No-logs", "Value"], platforms: ["windows", "macos", "linux", "ios", "android"], scores: [78, 70, 80, 83], tags: ["vpn", "privacy", "open-source", "security"] },
  { slug: "hotspot-shield", name: "Hotspot Shield", domain: "hotspotshield.com", category: "vpn", pricing: "FREEMIUM", company: "Pango",
    tagline: "Fast VPN with a free tier",
    description: "Hotspot Shield is a VPN known for fast speeds using its Hydra protocol, with a limited free plan and premium unlimited tiers.",
    pros: ["Fast speeds", "Free tier available", "Easy to use"], cons: ["Free is limited & ad-supported", "Privacy history questioned", "Fewer advanced features"],
    bestFor: ["Speed", "Casual use", "Free VPN"], platforms: ["windows", "macos", "ios", "android"], scores: [74, 68, 80, 76], tags: ["vpn", "privacy", "free", "security"] },

  // ── Cloud storage ──
  { slug: "box", name: "Box", domain: "box.com", category: "cloud", pricing: "FREEMIUM", company: "Box",
    tagline: "Cloud content management for businesses",
    description: "Box focuses on secure cloud content management and collaboration for enterprises, with strong compliance, governance and workflow features.",
    pros: ["Enterprise security", "Compliance & governance", "Integrations"], cons: ["Consumer features limited", "Pricey", "Overkill for individuals"],
    bestFor: ["Enterprises", "Compliance", "Business collaboration"], platforms: ["web", "windows", "macos", "ios", "android"], scores: [76, 72, 82, 86], tags: ["cloud-storage", "enterprise", "collaboration", "files"] },
  { slug: "mega", name: "MEGA", domain: "mega.io", category: "cloud", pricing: "FREEMIUM", company: "MEGA",
    tagline: "Encrypted cloud storage with a generous free tier",
    description: "MEGA offers end-to-end encrypted cloud storage with a large free allowance, chat and file sharing, focused on privacy.",
    pros: ["Big free storage", "End-to-end encryption", "Privacy-focused"], cons: ["Transfer quotas", "Past reputation baggage", "Recovery key risk"],
    bestFor: ["Free storage", "Privacy", "File sharing"], platforms: ["web", "windows", "macos", "linux", "ios", "android"], scores: [78, 70, 82, 80], tags: ["cloud-storage", "privacy", "encryption", "files"] },
  { slug: "tresorit", name: "Tresorit", domain: "tresorit.com", category: "cloud", pricing: "SUBSCRIPTION", company: "Tresorit",
    tagline: "End-to-end encrypted cloud storage for business",
    description: "Tresorit provides zero-knowledge, end-to-end encrypted cloud storage and sharing built for privacy-conscious businesses and professionals.",
    pros: ["Zero-knowledge encryption", "Business-grade", "Swiss privacy"], cons: ["Expensive", "No free tier", "Fewer integrations"],
    bestFor: ["Businesses", "Sensitive data", "Privacy"], platforms: ["web", "windows", "macos", "linux", "ios", "android"], scores: [76, 70, 74, 88], tags: ["cloud-storage", "encryption", "privacy", "business"] },

  // ── Email / Marketing ──
  { slug: "brevo", name: "Brevo", domain: "brevo.com", category: "marketing", pricing: "FREEMIUM", company: "Brevo",
    tagline: "All-in-one email, SMS and marketing platform",
    description: "Brevo (formerly Sendinblue) offers email marketing, SMS, automation, CRM and transactional email with a generous free tier priced by emails, not contacts.",
    pros: ["Priced by emails not contacts", "All-in-one", "Good free tier"], cons: ["Sending limits on free", "UI learning curve", "Deliverability varies"],
    bestFor: ["Small businesses", "Email + SMS", "Budget marketing"], platforms: ["web", "api"], scores: [79, 74, 82, 83], tags: ["email-marketing", "sms", "automation", "marketing"] },
  { slug: "activecampaign", name: "ActiveCampaign", domain: "activecampaign.com", category: "marketing", pricing: "SUBSCRIPTION", company: "ActiveCampaign",
    tagline: "Email marketing automation with built-in CRM",
    description: "ActiveCampaign combines powerful email marketing automation with a CRM, known for advanced automations and segmentation.",
    pros: ["Powerful automations", "Built-in CRM", "Good deliverability"], cons: ["Learning curve", "Pricing by contacts", "Can be complex"],
    bestFor: ["Automation", "SMBs", "Email + CRM"], platforms: ["web", "api"], scores: [79, 76, 82, 84], tags: ["email-marketing", "automation", "crm", "marketing"] },
  { slug: "getresponse", name: "GetResponse", domain: "getresponse.com", category: "marketing", pricing: "FREEMIUM", company: "GetResponse",
    tagline: "Email marketing, automation and webinars",
    description: "GetResponse is an all-in-one marketing platform with email, automation, landing pages and built-in webinars, aimed at small businesses.",
    pros: ["Includes webinars", "All-in-one", "Good value"], cons: ["UI dated in places", "Deliverability varies", "Feature sprawl"],
    bestFor: ["Small businesses", "Webinars", "Email marketing"], platforms: ["web"], scores: [77, 72, 80, 82], tags: ["email-marketing", "automation", "webinars", "marketing"] },
  { slug: "hootsuite", name: "Hootsuite", domain: "hootsuite.com", category: "marketing", pricing: "SUBSCRIPTION", company: "Hootsuite",
    tagline: "Social media management and scheduling",
    description: "Hootsuite lets teams schedule posts, monitor conversations and analyze performance across many social networks from one dashboard.",
    pros: ["Multi-network management", "Good analytics", "Team features"], cons: ["Pricey", "Interface dated", "No free plan now"],
    bestFor: ["Social teams", "Agencies", "Scheduling"], platforms: ["web", "ios", "android"], scores: [77, 72, 84, 83], tags: ["social-media", "scheduling", "marketing", "analytics"] },
  { slug: "later", name: "Later", domain: "later.com", category: "marketing", pricing: "FREEMIUM", company: "Later",
    tagline: "Visual social media planner, great for Instagram",
    description: "Later is a visual-first social media scheduler especially strong for Instagram, with a drag-and-drop calendar and link-in-bio tools.",
    pros: ["Visual planning", "Great for Instagram", "Link-in-bio"], cons: ["Post limits on free", "Fewer networks focus", "Analytics on paid"],
    bestFor: ["Instagram", "Creators", "Visual brands"], platforms: ["web", "ios", "android"], scores: [77, 72, 82, 82], tags: ["social-media", "scheduling", "instagram", "marketing"] },

  // ── Finance ──
  { slug: "cash-app", name: "Cash App", domain: "cash.app", category: "finance", pricing: "FREE", company: "Block",
    tagline: "Send money, bank and invest from your phone",
    description: "Cash App lets you send and receive money, get a debit card, and buy stocks and bitcoin, popular in the US for peer-to-peer payments.",
    pros: ["Easy P2P payments", "Investing & bitcoin", "Free basics"], cons: ["US-focused", "Support limited", "Scam targeting"],
    bestFor: ["P2P payments", "US users", "Simple investing"], platforms: ["ios", "android"], scores: [76, 68, 88, 78], tags: ["payments", "finance", "banking", "p2p"] },
  { slug: "robinhood", name: "Robinhood", domain: "robinhood.com", category: "finance", pricing: "FREEMIUM", company: "Robinhood",
    tagline: "Commission-free stock and crypto investing",
    description: "Robinhood popularized commission-free trading of stocks, ETFs, options and crypto with a simple mobile-first app.",
    pros: ["Commission-free", "Simple app", "Fractional shares"], cons: ["Gamification concerns", "Limited research", "Past outages"],
    bestFor: ["Beginner investors", "Mobile trading", "US users"], platforms: ["ios", "android", "web"], scores: [76, 70, 88, 78], tags: ["investing", "finance", "stocks", "crypto"] },
  { slug: "coinbase", name: "Coinbase", domain: "coinbase.com", category: "finance", pricing: "FREEMIUM", company: "Coinbase",
    tagline: "Buy, sell and store cryptocurrency",
    description: "Coinbase is a leading, publicly-listed cryptocurrency exchange known for ease of use, security and regulatory compliance.",
    pros: ["Easy to use", "Regulated & public", "Good security"], cons: ["Higher fees", "Support complaints", "Crypto volatility"],
    bestFor: ["Crypto beginners", "Buying crypto", "Secure storage"], platforms: ["web", "ios", "android"], scores: [76, 70, 90, 82], tags: ["crypto", "finance", "exchange", "bitcoin"] },
  { slug: "freshbooks", name: "FreshBooks", domain: "freshbooks.com", category: "finance", pricing: "SUBSCRIPTION", company: "FreshBooks",
    tagline: "Accounting and invoicing built for freelancers",
    description: "FreshBooks focuses on simple invoicing, expenses and time tracking for freelancers and service businesses, with a friendly interface.",
    pros: ["Great invoicing", "Easy for non-accountants", "Time tracking"], cons: ["Client limits per tier", "Less for product businesses", "Pricey scaling"],
    bestFor: ["Freelancers", "Service businesses", "Invoicing"], platforms: ["web", "ios", "android"], scores: [78, 72, 82, 84], tags: ["accounting", "invoicing", "finance", "freelance"] },
  { slug: "gusto", name: "Gusto", domain: "gusto.com", category: "finance", pricing: "SUBSCRIPTION", company: "Gusto",
    tagline: "Payroll, benefits and HR for small businesses",
    description: "Gusto handles payroll, benefits, and HR for small US businesses with a friendly interface and automated tax filings.",
    pros: ["Easy payroll", "Benefits & HR", "Automated taxes"], cons: ["US only", "Per-employee cost", "Support wait times"],
    bestFor: ["Small businesses", "Payroll", "US HR"], platforms: ["web"], scores: [77, 72, 82, 85], tags: ["payroll", "hr", "finance", "business"] },

  // ── CRM ──
  { slug: "zoho-crm", name: "Zoho CRM", domain: "zoho.com/crm", category: "crm", pricing: "FREEMIUM", company: "Zoho",
    tagline: "Affordable CRM within a huge business suite",
    description: "Zoho CRM offers full-featured sales CRM at accessible prices, integrated with the broad Zoho ecosystem of business apps.",
    pros: ["Great value", "Deep Zoho suite", "Customizable"], cons: ["UI can feel dense", "Suite complexity", "Support varies"],
    bestFor: ["SMBs", "Budget CRM", "Zoho users"], platforms: ["web", "ios", "android"], scores: [79, 74, 84, 84], tags: ["crm", "sales", "business", "saas"] },
  { slug: "close-crm", name: "Close", domain: "close.com", category: "crm", pricing: "SUBSCRIPTION", company: "Close",
    tagline: "CRM built for inside sales teams that call and email",
    description: "Close is a sales CRM with built-in calling, SMS and email designed to help inside sales teams communicate and close deals faster.",
    pros: ["Built-in calling & email", "Sales-focused", "Fast workflow"], cons: ["Pricey per seat", "Less for marketing", "SMB/mid-market focus"],
    bestFor: ["Inside sales", "SDR teams", "Startups"], platforms: ["web", "windows", "macos", "ios", "android"], scores: [77, 74, 76, 83], tags: ["crm", "sales", "calling", "saas"] },
  { slug: "apollo-io", name: "Apollo.io", domain: "apollo.io", category: "crm", pricing: "FREEMIUM", company: "Apollo",
    tagline: "Sales intelligence and outreach with a huge B2B database",
    description: "Apollo.io combines a massive B2B contact database with sales engagement and CRM tools for prospecting and outbound outreach.",
    pros: ["Huge contact database", "Prospecting + outreach", "Good free tier"], cons: ["Data accuracy varies", "Compliance care needed", "Feature overload"],
    bestFor: ["Sales prospecting", "Outbound", "Lead generation"], platforms: ["web", "chrome"], scores: [78, 76, 82, 80], tags: ["sales", "crm", "prospecting", "b2b"] },

  // ── No-code / Sites ──
  { slug: "carrd", name: "Carrd", domain: "carrd.co", category: "no-code", pricing: "FREEMIUM", company: "Carrd",
    tagline: "Simple, responsive one-page sites",
    description: "Carrd lets anyone build simple, responsive one-page websites — landing pages, profiles and portfolios — for free or a tiny yearly fee.",
    pros: ["Dead simple", "Very cheap", "Great for one-pagers"], cons: ["Single-page focus", "Limited for complex sites", "Basic features"],
    bestFor: ["Landing pages", "Link-in-bio", "Portfolios"], platforms: ["web"], scores: [78, 70, 82, 82], tags: ["website-builder", "no-code", "landing-page", "simple"] },
  { slug: "softr", name: "Softr", domain: "softr.io", category: "no-code", pricing: "FREEMIUM", company: "Softr",
    tagline: "Build apps and portals on top of Airtable and Sheets",
    description: "Softr turns Airtable or Google Sheets data into client portals, internal tools and websites with no code, using prebuilt blocks.",
    pros: ["Easy no-code apps", "Great with Airtable", "Prebuilt blocks"], cons: ["Depends on data source", "Pricing by usage", "Less custom logic"],
    bestFor: ["Client portals", "Internal tools", "No-code apps"], platforms: ["web"], scores: [78, 74, 76, 80], tags: ["no-code", "app-builder", "airtable", "portals"] },
  { slug: "glide", name: "Glide", domain: "glideapps.com", category: "no-code", pricing: "FREEMIUM", company: "Glide",
    tagline: "Turn spreadsheets into apps, no code",
    description: "Glide builds mobile and web apps from spreadsheet data with a visual editor and AI, ideal for internal tools and simple business apps.",
    pros: ["Fast app building", "AI-assisted", "Spreadsheet-based"], cons: ["Scaling limits", "Pricing by usage", "Less for complex apps"],
    bestFor: ["Internal apps", "Small business apps", "No-code"], platforms: ["web"], scores: [78, 76, 78, 80], tags: ["no-code", "app-builder", "spreadsheet", "mobile"] },

  // ── PDF ──
  { slug: "foxit", name: "Foxit PDF Editor", domain: "foxit.com", category: "pdf-tools", pricing: "SUBSCRIPTION", company: "Foxit",
    tagline: "Full-featured PDF editor and Acrobat alternative",
    description: "Foxit offers a fast, full-featured PDF editor with editing, forms, e-signatures and collaboration at a lower cost than Adobe Acrobat.",
    pros: ["Feature-rich", "Cheaper than Acrobat", "Fast & light"], cons: ["UI busy", "Upsells", "Occasional bugs"],
    bestFor: ["PDF editing", "Businesses", "Acrobat switchers"], platforms: ["windows", "macos", "web", "ios", "android"], scores: [78, 72, 82, 83], tags: ["pdf", "documents", "editor", "e-signature"] },
  { slug: "sejda", name: "Sejda PDF", domain: "sejda.com", category: "pdf-tools", pricing: "FREEMIUM", company: "Sejda",
    tagline: "Easy online and desktop PDF editing",
    description: "Sejda offers simple, privacy-conscious PDF editing, merging and conversion online or on desktop, with files auto-deleted after processing.",
    pros: ["Simple editing", "Privacy-friendly", "Web & desktop"], cons: ["Daily limits on free", "Fewer advanced tools", "Subscription for heavy use"],
    bestFor: ["Quick PDF edits", "Merging", "Privacy"], platforms: ["web", "windows", "macos", "linux"], scores: [78, 70, 78, 82], tags: ["pdf", "editor", "converter", "documents"] },

  // ── Browsers ──
  { slug: "google-chrome", name: "Google Chrome", domain: "google.com/chrome", category: "browser-extensions", pricing: "FREE", company: "Google",
    tagline: "The world's most popular web browser",
    description: "Google Chrome is the dominant web browser, known for speed, a vast extension library and deep Google integration, built on the open-source Chromium.",
    pros: ["Fast & compatible", "Huge extension library", "Syncs with Google"], cons: ["Heavy on RAM", "Privacy concerns", "Google tracking"],
    bestFor: ["General browsing", "Web developers", "Google users"], platforms: ["windows", "macos", "linux", "ios", "android"], scores: [80, 74, 98, 86], tags: ["browser", "google", "chromium", "web"] },
  { slug: "microsoft-edge", name: "Microsoft Edge", domain: "microsoft.com/edge", category: "browser-extensions", pricing: "FREE", company: "Microsoft",
    tagline: "Microsoft's fast, Chromium-based browser",
    description: "Microsoft Edge is a Chromium-based browser with strong performance, vertical tabs, Copilot AI and good efficiency features, bundled with Windows.",
    pros: ["Fast & efficient", "Chromium compatible", "Built-in AI & features"], cons: ["Microsoft nudges", "Privacy considerations", "Feature bloat"],
    bestFor: ["Windows users", "Efficiency", "General browsing"], platforms: ["windows", "macos", "linux", "ios", "android"], scores: [79, 76, 90, 85], tags: ["browser", "microsoft", "chromium", "web"] },
  { slug: "opera", name: "Opera", domain: "opera.com", category: "browser-extensions", pricing: "FREE", company: "Opera",
    tagline: "Feature-packed browser with built-in VPN and AI",
    description: "Opera is a Chromium-based browser with a free built-in VPN, ad blocker, messengers sidebar and an integrated AI assistant.",
    pros: ["Built-in free VPN", "Ad blocker & sidebar", "Feature-rich"], cons: ["Ownership scrutiny", "VPN is a proxy", "Not for minimalists"],
    bestFor: ["Feature seekers", "Built-in VPN", "General browsing"], platforms: ["windows", "macos", "linux", "ios", "android"], scores: [78, 74, 84, 80], tags: ["browser", "vpn", "chromium", "web"] },
  { slug: "tor-browser", name: "Tor Browser", domain: "torproject.org", category: "browser-extensions", pricing: "OPEN_SOURCE", company: "Tor Project", openSource: true,
    tagline: "Anonymous browsing through the Tor network",
    description: "Tor Browser routes your traffic through the Tor network for strong anonymity and censorship resistance, free and open source.",
    pros: ["Strong anonymity", "Censorship resistant", "Free & open source"], cons: ["Slow speeds", "Some sites block Tor", "Not for everyday use"],
    bestFor: ["Anonymity", "Activists", "Censorship circumvention"], platforms: ["windows", "macos", "linux", "android"], scores: [80, 70, 82, 88], tags: ["browser", "privacy", "anonymity", "open-source"] },

  // ── Analytics ──
  { slug: "matomo", name: "Matomo", domain: "matomo.org", category: "marketing", pricing: "FREEMIUM", company: "Matomo", openSource: true,
    tagline: "Open-source, privacy-respecting web analytics",
    description: "Matomo is an open-source, self-hostable analytics platform that gives you full data ownership and GDPR compliance, a Google Analytics alternative.",
    pros: ["Own your data", "Open source & self-hostable", "GDPR-friendly"], cons: ["Self-host effort", "Cloud is paid", "Heavier than lightweight tools"],
    bestFor: ["Privacy-focused sites", "Data ownership", "Compliance"], platforms: ["web", "self-hosted"], scores: [82, 74, 82, 88], tags: ["analytics", "open-source", "privacy", "web"] },
  { slug: "amplitude", name: "Amplitude", domain: "amplitude.com", category: "marketing", pricing: "FREEMIUM", company: "Amplitude",
    tagline: "Product analytics for digital growth",
    description: "Amplitude is a product analytics platform for understanding user behavior, retention and growth with powerful behavioral analysis.",
    pros: ["Deep product analytics", "Behavioral cohorts", "Good free tier"], cons: ["Complex setup", "Costs at scale", "Learning curve"],
    bestFor: ["Product teams", "Growth", "SaaS"], platforms: ["web", "api"], scores: [80, 78, 84, 85], tags: ["analytics", "product", "growth", "marketing"] },

  // ── Streaming / Media ──
  { slug: "netflix", name: "Netflix", domain: "netflix.com", category: "streaming", pricing: "SUBSCRIPTION", company: "Netflix", featured: true,
    tagline: "The world's leading video streaming service",
    description: "Netflix streams a vast library of films, series and original productions worldwide, with personalized recommendations and downloads.",
    pros: ["Huge original content", "Great recommendations", "Works everywhere"], cons: ["Price rises", "Content rotates out", "Password-sharing crackdown"],
    bestFor: ["Movies & series", "Binge-watching", "Families"], platforms: ["web", "ios", "android", "windows", "macos"], scores: [78, 74, 97, 88], tags: ["streaming", "video", "movies", "tv"] },
  { slug: "youtube", name: "YouTube", domain: "youtube.com", category: "streaming", pricing: "FREEMIUM", company: "Google", featured: true,
    tagline: "The world's largest video platform",
    description: "YouTube hosts billions of videos from creators worldwide — entertainment, education, music and live streams — free with ads or ad-free via Premium.",
    pros: ["Endless free content", "Huge creator ecosystem", "Learn anything"], cons: ["Ads without Premium", "Algorithm rabbit holes", "Moderation issues"],
    bestFor: ["Video content", "Learning", "Creators"], platforms: ["web", "ios", "android", "windows", "macos"], scores: [80, 76, 99, 88], tags: ["streaming", "video", "creators", "google"] },
  { slug: "plex", name: "Plex", domain: "plex.tv", category: "streaming", pricing: "FREEMIUM", company: "Plex",
    tagline: "Organize and stream your own media library",
    description: "Plex turns your personal media collection into a beautiful, streamable library across devices, plus free ad-supported movies and live TV.",
    pros: ["Great media server", "Streams anywhere", "Free content too"], cons: ["Remote streaming needs Pass", "Setup effort", "Server hardware needed"],
    bestFor: ["Media collectors", "Home servers", "Cord-cutters"], platforms: ["web", "windows", "macos", "linux", "ios", "android"], scores: [80, 72, 84, 84], tags: ["media-server", "streaming", "video", "self-hosted"] },
  { slug: "jellyfin", name: "Jellyfin", domain: "jellyfin.org", category: "streaming", pricing: "OPEN_SOURCE", company: "Jellyfin", openSource: true,
    tagline: "Free, open-source media server with no strings",
    description: "Jellyfin is a completely free, open-source media server that streams your movies, shows and music with no premium tiers or tracking.",
    pros: ["Completely free & open source", "No tracking", "Self-hosted control"], cons: ["Setup effort", "Fewer polished apps", "No official content"],
    bestFor: ["Self-hosters", "Privacy", "Media libraries"], platforms: ["web", "windows", "macos", "linux", "android"], scores: [82, 72, 78, 86], tags: ["media-server", "open-source", "streaming", "self-hosted"] },
  { slug: "audible", name: "Audible", domain: "audible.com", category: "streaming", pricing: "SUBSCRIPTION", company: "Amazon",
    tagline: "The largest audiobook service",
    description: "Audible offers the biggest catalog of audiobooks and originals with a credit-based subscription, integrated with Amazon and Kindle.",
    pros: ["Huge audiobook catalog", "Great app", "Amazon/Kindle sync"], cons: ["Credit system pricey", "DRM lock-in", "Amazon ecosystem"],
    bestFor: ["Audiobook listeners", "Commuters", "Readers"], platforms: ["web", "ios", "android"], scores: [76, 68, 90, 85], tags: ["audiobooks", "streaming", "amazon", "audio"] },
  { slug: "deezer", name: "Deezer", domain: "deezer.com", category: "streaming", pricing: "FREEMIUM", company: "Deezer",
    tagline: "Music streaming with hi-fi and a large catalog",
    description: "Deezer streams millions of tracks with a free tier, HiFi lossless audio and features like Flow personalized radio and lyrics.",
    pros: ["Large catalog", "HiFi lossless option", "Free tier"], cons: ["Smaller user base", "App less polished", "Discovery weaker"],
    bestFor: ["Music fans", "Lossless on budget", "Discovery"], platforms: ["web", "ios", "android", "windows", "macos"], scores: [76, 72, 82, 82], tags: ["music", "streaming", "audio", "hi-fi"] },

  // ── Gaming ──
  { slug: "gog", name: "GOG", domain: "gog.com", category: "games", pricing: "FREE", company: "CD Projekt",
    tagline: "DRM-free games store from CD Projekt",
    description: "GOG (Good Old Games) sells DRM-free PC games — classics and new titles — that you truly own, with GOG Galaxy to unify your libraries.",
    pros: ["DRM-free ownership", "Classic games", "No always-online"], cons: ["Smaller catalog", "Fewer AAA day-one", "Less social"],
    bestFor: ["DRM-free fans", "Retro gaming", "Game ownership"], platforms: ["windows", "macos", "linux"], scores: [79, 68, 82, 88], tags: ["gaming", "store", "drm-free", "pc"] },
  { slug: "unity", name: "Unity", domain: "unity.com", category: "developer-tools", pricing: "FREEMIUM", company: "Unity",
    tagline: "Popular cross-platform game engine",
    description: "Unity is a widely used real-time 3D engine for building games and interactive experiences across mobile, console, PC, AR and VR.",
    pros: ["Cross-platform", "Huge asset store", "Great for mobile/indie"], cons: ["Pricing controversy", "Performance tuning", "Learning curve"],
    bestFor: ["Game developers", "Mobile games", "AR/VR"], platforms: ["windows", "macos", "linux"], scores: [82, 76, 88, 82], tags: ["game-engine", "3d", "developer", "gaming"] },
  { slug: "godot", name: "Godot Engine", domain: "godotengine.org", category: "developer-tools", pricing: "OPEN_SOURCE", company: "Godot", openSource: true,
    tagline: "Free, open-source game engine",
    description: "Godot is a fully free and open-source game engine with a lightweight editor, a friendly scene system and its own scripting language, GDScript.",
    pros: ["Free & open source", "Lightweight", "Growing fast"], cons: ["Smaller ecosystem", "Fewer AAA features", "3D catching up"],
    bestFor: ["Indie devs", "2D games", "Open-source fans"], platforms: ["windows", "macos", "linux"], scores: [83, 74, 82, 86], tags: ["game-engine", "open-source", "developer", "gaming"] },

  // ── Education ──
  { slug: "skillshare", name: "Skillshare", domain: "skillshare.com", category: "education", pricing: "SUBSCRIPTION", company: "Skillshare",
    tagline: "Online classes for creative and practical skills",
    description: "Skillshare offers thousands of project-based classes in design, illustration, business and more via a subscription, taught by practitioners.",
    pros: ["Creative focus", "Project-based", "One subscription"], cons: ["No certificates", "Quality varies", "Subscription only"],
    bestFor: ["Creatives", "Hobbies", "Practical skills"], platforms: ["web", "ios", "android"], scores: [77, 72, 84, 82], tags: ["education", "courses", "creative", "learning"] },
  { slug: "codecademy", name: "Codecademy", domain: "codecademy.com", category: "education", pricing: "FREEMIUM", company: "Codecademy",
    tagline: "Learn to code with interactive lessons",
    description: "Codecademy teaches programming through hands-on, in-browser interactive lessons across many languages and career paths.",
    pros: ["Interactive & hands-on", "Structured paths", "Beginner-friendly"], cons: ["Best features paid", "Less depth than some", "Practice environment limits"],
    bestFor: ["Coding beginners", "Career switchers", "Interactive learning"], platforms: ["web"], scores: [79, 74, 86, 84], tags: ["education", "coding", "learning", "programming"] },
  { slug: "freecodecamp", name: "freeCodeCamp", domain: "freecodecamp.org", category: "education", pricing: "FREE", company: "freeCodeCamp", openSource: true,
    tagline: "Learn to code for free with certifications",
    description: "freeCodeCamp is a non-profit offering a completely free, self-paced coding curriculum with certifications and thousands of hours of content.",
    pros: ["Completely free", "Certifications", "Huge curriculum & community"], cons: ["Self-directed", "Less hand-holding", "No live support"],
    bestFor: ["Coding beginners", "Self-learners", "Free learning"], platforms: ["web"], scores: [82, 74, 88, 90], tags: ["education", "coding", "free", "non-profit"] },
  { slug: "brilliant", name: "Brilliant", domain: "brilliant.org", category: "education", pricing: "SUBSCRIPTION", company: "Brilliant",
    tagline: "Interactive courses in math, science and CS",
    description: "Brilliant teaches math, science and computer science through interactive, visual, problem-solving lessons that build intuition.",
    pros: ["Interactive & visual", "Builds intuition", "Great for STEM"], cons: ["Subscription only", "Narrow subjects", "Not deep enough for experts"],
    bestFor: ["STEM learners", "Students", "Curious minds"], platforms: ["web", "ios", "android"], scores: [78, 74, 82, 85], tags: ["education", "math", "science", "learning"] },
  { slug: "wolfram-alpha", name: "Wolfram Alpha", domain: "wolframalpha.com", category: "education", pricing: "FREEMIUM", company: "Wolfram",
    tagline: "Computational knowledge engine",
    description: "Wolfram Alpha computes answers across math, science, engineering and more, showing step-by-step solutions, a favorite for students.",
    pros: ["Powerful computation", "Step-by-step solutions", "Broad knowledge"], cons: ["Steps need Pro", "Niche interface", "Not a search engine"],
    bestFor: ["Students", "Math & science", "Homework help"], platforms: ["web", "ios", "android"], scores: [78, 80, 86, 88], tags: ["education", "math", "computation", "science"] },
];

const ALTERNATIVES: [string, string, number][] = [
  ["dall-e", "midjourney", 82], ["dall-e", "adobe-firefly", 80], ["character-ai", "poe", 74],
  ["poe", "chatgpt", 70], ["mistral-ai", "chatgpt", 72], ["mistral-ai", "ollama", 74],
  ["quillbot", "grammarly", 82], ["photoroom", "remove-bg", 86], ["remove-bg", "photoroom", 86],
  ["freepik", "adobe-firefly", 66], ["adobe-firefly", "dall-e", 80], ["phind", "perplexity", 80],
  ["google-docs", "microsoft-word", 88], ["google-sheets", "microsoft-excel", 90], ["microsoft-excel", "google-sheets", 90],
  ["google-sheets", "airtable", 66], ["roam-research", "obsidian", 82], ["roam-research", "logseq", 84],
  ["craft-docs", "notion", 74], ["bear-app", "obsidian", 74], ["joplin", "evernote", 82],
  ["joplin", "obsidian", 76], ["motion", "todoist", 66], ["fantastical", "google-keep", 50],
  ["adobe-xd", "figma", 84], ["adobe-xd", "sketch", 80], ["invision", "figma", 76],
  ["spline", "blender", 60], ["pixelmator-pro", "adobe-photoshop", 82], ["pixelmator-pro", "affinity-photo", 80],
  ["capture-one", "adobe-photoshop", 64], ["jira", "linear", 84], ["jira", "asana", 76],
  ["confluence", "notion", 76], ["bitbucket", "github", 86], ["bitbucket", "gitlab", 84],
  ["circleci", "github", 60], ["circleci", "gitlab", 66], ["datadog", "grafana", 78],
  ["datadog", "sentry", 66], ["algolia", "meilisearch", 88], ["cypress", "playwright", 90],
  ["playwright", "cypress", 90], ["nextjs", "astro", 74], ["nextjs", "react", 70],
  ["react", "vue", 80], ["tailwindcss", "bootstrap", 76], ["astro", "nextjs", 74],
  ["skype", "zoom", 72], ["skype", "google-meet", 70], ["webex", "zoom", 84],
  ["element", "signal", 66], ["element", "mattermost", 70], ["lastpass", "bitwarden", 84],
  ["lastpass", "1password", 82], ["nordpass", "bitwarden", 82], ["keeper", "1password", 80],
  ["malwarebytes", "bitdefender", 78], ["bitdefender", "malwarebytes", 78], ["ublock-origin", "brave", 66],
  ["cyberghost", "nordvpn", 84], ["private-internet-access", "nordvpn", 82], ["hotspot-shield", "windscribe", 74],
  ["box", "dropbox", 80], ["box", "google-drive", 74], ["mega", "google-drive", 76],
  ["tresorit", "proton-drive", 82], ["brevo", "mailchimp", 84], ["activecampaign", "mailchimp", 82],
  ["getresponse", "mailchimp", 80], ["hootsuite", "buffer", 86], ["later", "buffer", 82],
  ["cash-app", "paypal", 78], ["robinhood", "coinbase", 66], ["coinbase", "robinhood", 66],
  ["freshbooks", "quickbooks", 82], ["freshbooks", "wave-accounting", 80], ["gusto", "quickbooks", 60],
  ["zoho-crm", "hubspot", 80], ["zoho-crm", "salesforce", 76], ["close-crm", "pipedrive", 82],
  ["apollo-io", "hubspot", 66], ["carrd", "wix", 66], ["softr", "glide", 84],
  ["glide", "softr", 84], ["foxit", "adobe-acrobat", 86], ["sejda", "ilovepdf", 82],
  ["google-chrome", "microsoft-edge", 86], ["google-chrome", "brave", 80], ["microsoft-edge", "google-chrome", 86],
  ["opera", "brave", 76], ["tor-browser", "firefox", 66], ["matomo", "google-analytics", 84],
  ["matomo", "plausible", 80], ["amplitude", "mixpanel", 88], ["netflix", "youtube", 50],
  ["plex", "jellyfin", 90], ["jellyfin", "plex", 90], ["audible", "spotify", 50],
  ["deezer", "spotify", 84], ["deezer", "tidal", 78], ["gog", "steam", 80],
  ["unity", "godot", 84], ["godot", "unity", 84], ["skillshare", "udemy", 78],
  ["codecademy", "freecodecamp", 84], ["freecodecamp", "codecademy", 84], ["brilliant", "khan-academy", 76],
  ["wolfram-alpha", "khan-academy", 60],
];

async function createTool(seed: ToolSeed): Promise<boolean> {
  const category = await prisma.category.findUnique({ where: { slug: seed.category } });
  if (!category) { console.warn(`[expand-catalog-3] category "${seed.category}" missing — skipping ${seed.slug}`); return false; }

  let companyId: string | undefined;
  if (seed.company) {
    const companySlug = seed.company.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const company = await prisma.company.upsert({ where: { slug: companySlug }, create: { slug: companySlug, name: seed.company }, update: {} });
    companyId = company.id;
  }

  const [alternativeScore, aiScore, popularityScore, trustScore] = seed.scores;
  const tool = await prisma.tool.create({
    data: {
      slug: seed.slug, name: seed.name, tagline: seed.tagline, description: seed.description,
      websiteUrl: `https://${seed.domain}`, logoUrl: favicon(seed.domain), pricingModel: seed.pricing,
      pros: seed.pros, cons: seed.cons, bestFor: seed.bestFor,
      aiSummary: `${seed.name} — ${seed.tagline}. ${seed.description.split(". ")[0]}.`,
      status: "PUBLISHED", publishedAt: new Date(), featured: seed.featured ?? false, verified: true,
      isOpenSource: seed.openSource ?? false, alternativeScore, aiScore, popularityScore, trustScore,
      viewCount: Math.round(popularityScore * 137), upvotes: Math.round(popularityScore * 3.2),
      categoryId: category.id, companyId,
      seoTitle: `${seed.name} — Reviews, Pricing & Best Alternatives`,
      seoDesc: `${seed.tagline}. Compare ${seed.name} features, pricing, pros & cons and find the best ${seed.name} alternatives.`,
      keywords: [`${seed.name.toLowerCase()} alternatives`, `${seed.name.toLowerCase()} review`, ...seed.tags],
    },
  });

  for (const platformSlug of seed.platforms) {
    const platform = await prisma.platform.findUnique({ where: { slug: platformSlug } });
    if (!platform) continue;
    await prisma.toolPlatform.create({ data: { toolId: tool.id, platformId: platform.id } }).catch(() => {});
  }
  for (const tagName of seed.tags) {
    const tagSlug = tagName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const tag = await prisma.tag.upsert({ where: { slug: tagSlug }, create: { slug: tagSlug, name: tagName }, update: {} });
    await prisma.toolTag.create({ data: { toolId: tool.id, tagId: tag.id } }).catch(() => {});
  }
  return true;
}

async function run() {
  let added = 0;
  try {
    for (const seed of TOOLS) {
      const existing = await prisma.tool.findUnique({ where: { slug: seed.slug }, select: { id: true } });
      if (existing) continue;
      const ok = await createTool(seed).catch((e) => { console.warn(`[expand-catalog-3] failed to add ${seed.slug}:`, e); return false; });
      if (ok) added += 1;
    }
    let edges = 0;
    for (const [sourceSlug, targetSlug, matchScore] of ALTERNATIVES) {
      const [source, target] = await Promise.all([
        prisma.tool.findUnique({ where: { slug: sourceSlug }, select: { id: true } }),
        prisma.tool.findUnique({ where: { slug: targetSlug }, select: { id: true } }),
      ]);
      if (!source || !target) continue;
      for (const [a, b] of [[source.id, target.id], [target.id, source.id]] as const) {
        await prisma.alternative.upsert({
          where: { sourceToolId_targetToolId: { sourceToolId: a, targetToolId: b } },
          create: { sourceToolId: a, targetToolId: b, matchScore }, update: {},
        }).then(() => { edges += 1; }).catch(() => {});
      }
    }
    console.log(`[expand-catalog-3] Added ${added} new tools and ${edges} alternative edges.`);
  } catch (err) {
    console.warn("[expand-catalog-3] Expansion failed (deploy will continue).", err);
  } finally {
    await prisma.$disconnect().catch(() => {});
  }
}

run();
